### ISSUE TITLE
problems with importing pseudopy

### ISSUE THREAD

**Issue by francispoulin** [andrenarchy/pseudopy#2]
I just installed pseudopy on my ubuntu machine and that seemed to go smoothly.

However, when I try importing it I get the following error.

I am sorry to bug you with this but if you have any advice on how to fix this I would be very keen to start playing with this library.  It looks great!

>>> import pseudopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pseudopy/__init__.py", line 5, in <module>
    from .normal import Normal, NormalEvals
  File "/usr/local/lib/python2.7/dist-packages/pseudopy/normal.py", line 3, in <module>
    import shapely.geometry as geom
ImportError: No module named shapely.geometry

**Comment by andrenarchy** [comment]
Thanks for reporting the issue! I fixed the dependencies in `setup.py` so reinstalling pseudopy should also pull in the dependencies. If you are on Debian/Ubuntu you probably want to install the dependencies with apt, see [readme](https://github.com/andrenarchy/pseudopy#installation).

**Comment by francispoulin** [comment]
Thanks for the quick fix.  I wanted to confirm that I reinstalled it and it ran beautifully.  Now to learn more how to use this library!

**Comment by andrenarchy** [comment]
Great!
